# TODO: CATEGORIAS ENDPOINTS
# Obtener todas las categorías
GET http://localhost:3000/api/categoria HTTP/1.1

###

# Obtener una categoría por ID
GET http://localhost:3000/api/categoria/1 HTTP/1.1

###

# Crear una nueva categoría
POST http://localhost:3000/api/categoria HTTP/1.1
Content-Type: application/json

{
  "nombre": "Buso",
  "descripcion": "Categoría de buso para hombre y mujer"
}

###

# Actualizar una categoría (PATCH)
PATCH http://localhost:3000/api/categoria/2 HTTP/1.1
Content-Type: application/json

{
   "nombre": "pantalonetas",
  "descripcion": "Categoría de pantalonetas para hombre y mujer"
}

###

# Eliminar una categoría
DELETE http://localhost:3000/api/categoria/2 HTTP/1.1

###

# TODO: PAISES ENDPOINTS
# Obtener todos los países
GET http://localhost:3000/api/pais HTTP/1.1

###

# Obtener un país por ID
GET http://localhost:3000/api/pais/1 HTTP/1.1

###

# Crear un nuevo país
POST http://localhost:3000/api/pais HTTP/1.1
Content-Type: application/json

{
  "nombre": "Mexico",
  "codigo": "MX"
}

###

# Actualizar un país (PATCH)
PATCH http://localhost:3000/api/pais/1 HTTP/1.1
Content-Type: application/json

{ 
  "nombre": "Estados Unidos",
  "codigo": "US"
}

###

# Eliminar un país
DELETE http://localhost:3000/api/pais/3 HTTP/1.1

###
# TODO: USUARIOS ENDPOINTS

# Obtener todos los usuarios
GET http://localhost:3000/api/usuario HTTP/1.1

###

# Obtener un usuario por ID
GET http://localhost:3000/api/usuario/ebd4089c-b4e3-466f-9393-eaf844654057 HTTP/1.1

###

# Crear un nuevo usuario con persona
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "usuario": {
    "username": "ana123",
    "password": "Segura123",
    "avatar": "https://miavatar.com/ana.png",
    "activo": true
  },
  "persona": {
    "nombre": "Ana",
    "apellido": "Martinez",
    "correo": "ana.martinez@example.com",
    "telefono": 312345678,
    "genero": "F",
    "ciudad": "Bogotá",
    "edad": 28,
    "id_pais": 1
  }
}

###

# Actualizar un usuario (PATCH)
PATCH http://localhost:3000/api/usuario/550983de-642c-4c3b-82ec-96c0a7b3c9c9 HTTP/1.1
Content-Type: application/json

{
  "usuario": {
    "username": "laura321",
    "password": "LauraPass2025",
    "avatar": "https://miavatar.com/laura.png",
    "activo": true
  },
  "persona": {
    "nombres": "Laura",
    "apellidos": "Martínez",
    "correo": "laura.martinez@example.com",
    "telefono": 310123456,
    "genero": "F",
    "ciudad": "Bogotá",
    "edad": 28,
    "id_pais": 2
  }
}


###
# Eliminar un usuario
DELETE http://localhost:3000/api/usuario/ee0aa912-15c7-4086-9227-05b8b266f5e5 HTTP/1.1

###

#TODO: LOGIN ENDPOINTS
# Login
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "laura321",
  "password": "LauraPass2025"
}


###
# TODO: COLOR ENDPOINTS

GET http://localhost:3000/api/color HTTP/1.1

###

# Obtener una color por ID
GET http://localhost:3000/api/color/1 HTTP/1.1

###

# Crear una nueva color
POST http://localhost:3000/api/color HTTP/1.1
Content-Type: application/json

{
  "color": "negro"
}

###

# Actualizar una color (PATCH)
PATCH http://localhost:3000/api/color/1 HTTP/1.1
Content-Type: application/json

{
  "color": "gris"
}

###

# Eliminar una color
DELETE http://localhost:3000/api/color/2 HTTP/1.1

###

# TODO: TALLA ENDPOINTS

GET http://localhost:3000/api/talla HTTP/1.1

###

# Obtener una talla por ID
GET http://localhost:3000/api/talla/1 HTTP/1.1

###

# Crear una nueva talla
POST http://localhost:3000/api/talla HTTP/1.1
Content-Type: application/json

{
  "talla": "m"
}

###

# Actualizar una talla (PATCH)
PATCH http://localhost:3000/api/talla/1 HTTP/1.1
Content-Type: application/json

{
  "talla": "l"
}

###

# Eliminar una talla
DELETE http://localhost:3000/api/talla/2 HTTP/1.1

###
# TODO: PROVEEDOR ENDPOINTS

# Obtener todos los proveedores
GET http://localhost:3000/api/proveedor HTTP/1.1

###

# Obtener un proveedor por ID
GET http://localhost:3000/api/proveedor/1 HTTP/1.1

###

# Crear un nuevo proveedor
POST http://localhost:3000/api/proveedor HTTP/1.1
Content-Type: application/json

{
  "proveedor": {
    "razon_social": "Distribuciones ll",
    "marca": "ll"
  },
  "persona": {
    "nombres": "cristian",
    "apellidos": "sss",
    "correo": "cristian.pals@example.com",
    "telefono": 2222,
    "genero": "M",
    "ciudad": "Florencia",
    "edad": 26,
    "id_pais": 2
  }
}

###

# Actualizar un proveedor (PATCH)
PATCH http://localhost:3000/api/proveedor/1 HTTP/1.1
Content-Type: application/json

{
  "proveedor": {
    "razon_social": "Distribuciones carrf",
    "marca": "carrgf"
  },
  "persona": {
    "nombres": "mario",
    "apellidos": "222",
    "correo": "marioi.pals@example.com",
    "telefono": 3333,
    "genero": "F",
    "ciudad": "Medellin",
    "edad": 30,
    "id_pais": 1
  }
}

###

# Eliminar un proveedor
DELETE http://localhost:3000/api/proveedor/2 HTTP/1.1
