# TODO: CATEGORIAS ENDPOINTS
# Obtener todas las categorías
GET http://localhost:3000/api/categoria HTTP/1.1

###

# Obtener una categoría por ID
GET http://localhost:3000/api/categoria/1 HTTP/1.1

###

# Crear una nueva categoría
POST http://localhost:3000/api/categoria HTTP/1.1
Content-Type: application/json

{
  "nombre": "pantalones",
  "descripcion": "Categoría de pantalones para hombre y mujer"
}

###

# Actualizar una categoría (PATCH)
PATCH http://localhost:3000/api/categoria/2 HTTP/1.1
Content-Type: application/json

{
   "nombre": "pantalonetas",
  "descripcion": "Categoría de pantalonetas para hombre y mujer"
}

###

# Eliminar una categoría
DELETE http://localhost:3000/api/categoria/2 HTTP/1.1

###

# TODO: PAISES ENDPOINTS
# Obtener todos los países
GET http://localhost:3000/api/pais HTTP/1.1

###

# Obtener un país por ID
GET http://localhost:3000/api/pais/1 HTTP/1.1

###

# Crear un nuevo país
POST http://localhost:3000/api/pais HTTP/1.1
Content-Type: application/json

{
  "nombre": "Mexico",
  "codigo": "MX"
}

###

# Actualizar un país (PATCH)
PATCH http://localhost:3000/api/pais/1 HTTP/1.1
Content-Type: application/json

{ 
  "nombre": "Estados Unidos",
  "codigo": "US"
}

###

# Eliminar un país
DELETE http://localhost:3000/api/pais/3 HTTP/1.1

###
# TODO: USUARIOS ENDPOINTS

# Obtener todos los usuarios
GET http://localhost:3000/api/usuario HTTP/1.1

###

# Obtener un usuario por ID
GET http://localhost:3000/api/usuario/ebd4089c-b4e3-466f-9393-eaf844654057 HTTP/1.1

###

# Crear un nuevo usuario con persona
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "usuario": {
    "username": "ana_dev77",
    "password": "AnaPass2025!",
    "avatar": "https://miavatar.com/ana.png",
    "activo": true
  },
  "persona": {
    "nombre": "Ana",
    "apellido": "Gómez López",
    "correo": "ana.gomez@example.com",
    "telefono": 311654987,
    "genero": "F",
    "ciudad": "Bogotá",
    "edad": 29,
    "id_pais": 1
  }
}


###

# Actualizar un usuario (PATCH)
PATCH http://localhost:3000/api/usuario/550983de-642c-4c3b-82ec-96c0a7b3c9c9 HTTP/1.1
Content-Type: application/json

{
  "usuario": {
    "username": "carlos_dev89",
    "password": "SecurePass!2025",
    "avatar": "https://miavatar.com/carlos.png",
    "activo": true
  },
  "persona": {
    "nombres": "Carlos",
    "apellidos": "Ramírez Torres",
    "correo": "c.ramirez89@example.com",
    "telefono": 320987654,
    "genero": "M",
    "ciudad": "Medellín",
    "edad": 34,
    "id_pais": 3
  }
}



###
# Eliminar un usuario
DELETE http://localhost:3000/api/usuario/97d151db-a213-497e-a3cf-6398c9836cc0 HTTP/1.1

###

#TODO: LOGIN ENDPOINTS
# Login
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "ana_dev77",
  "password": "AnaPass2025!"
}


###
# TODO: COLOR ENDPOINTS

GET http://localhost:3000/api/color HTTP/1.1

###

# Obtener una color por ID
GET http://localhost:3000/api/color/1 HTTP/1.1

###

# Crear una nueva color
POST http://localhost:3000/api/color HTTP/1.1
Content-Type: application/json

{
  "color": "blanco"
}

###

# Actualizar una color (PATCH)
PATCH http://localhost:3000/api/color/1 HTTP/1.1
Content-Type: application/json

{
  "color": "gris"
}

###

# Eliminar una color
DELETE http://localhost:3000/api/color/2 HTTP/1.1

###

# TODO: TALLA ENDPOINTS

GET http://localhost:3000/api/talla HTTP/1.1

###

# Obtener una talla por ID
GET http://localhost:3000/api/talla/1 HTTP/1.1

###

# Crear una nueva talla
POST http://localhost:3000/api/talla HTTP/1.1
Content-Type: application/json

{
  "talla": "l"
}

###

# Actualizar una talla (PATCH)
PATCH http://localhost:3000/api/talla/1 HTTP/1.1
Content-Type: application/json

{
  "talla": "l"
}

###

# Eliminar una talla
DELETE http://localhost:3000/api/talla/2 HTTP/1.1

###
# TODO: PROVEEDOR ENDPOINTS

# Obtener todos los proveedores
GET http://localhost:3000/api/proveedor HTTP/1.1

###

# Obtener un proveedor por ID
GET http://localhost:3000/api/proveedor/1 HTTP/1.1

###

# Crear un nuevo proveedor
POST http://localhost:3000/api/proveedor HTTP/1.1
Content-Type: application/json

{
  "proveedor": {
    "razon_social": "Distribuciones ll",
    "marca": "ll"
  },
  "persona": {
    "nombres": "cristian",
    "apellidos": "sss",
    "correo": "cristian.pals@example.com",
    "telefono": 2222,
    "genero": "M",
    "ciudad": "Florencia",
    "edad": 26,
    "id_pais": 2
  }
}

###

# Actualizar un proveedor (PATCH)
PATCH http://localhost:3000/api/proveedor/1 HTTP/1.1
Content-Type: application/json

{
  "proveedor": {
    "razon_social": "Distribuciones carrf",
    "marca": "carrgf"
  },
  "persona": {
    "nombres": "mario",
    "apellidos": "222",
    "correo": "marioi.pals@example.com",
    "telefono": 3333,
    "genero": "F",
    "ciudad": "Medellin",
    "edad": 30,
    "id_pais": 1
  }
}

###

# Eliminar un proveedor
DELETE http://localhost:3000/api/proveedor/2 HTTP/1.1

###
# TODO: CLIENTE ENDPOINTS

# Obtener todos los cliente
GET http://localhost:3000/api/cliente HTTP/1.1

###

# Obtener un cliente por ID
GET http://localhost:3000/api/cliente/75b9d4ac-3306-4f35-804d-407b5aef7f35 HTTP/1.1

###

# Crear un nuevo cliente
POST http://localhost:3000/api/cliente HTTP/1.1
Content-Type: application/json

{
  "cliente": {
    "direccion": "cr 31 # 20 a asur 61",
    "activo": true
  },
  "persona": {
    "nombre": "cristian",
    "apellido": "sss",
    "correo": "cristian.pals@example.com",
    "telefono": 2222,
    "genero": "M",
    "ciudad": "Florencia",
    "edad": 26,
    "id_pais": 2
  }
}

###

# Actualizar un cliente (PATCH)
PATCH http://localhost:3000/api/cliente/e48a4358-8b92-44a2-a7ce-ca2935b48a82 HTTP/1.1
Content-Type: application/json

{
  "cliente": {
    "direccion": "cr 31 # 2222 a asur 61",
    "activo": false
  },
  "persona": {
    "nombre": "eder",
    "apellido": "rivv",
    "correo": "eder.pals@example.com",
    "telefono": 11111,
    "genero": "M",
    "ciudad": "Neiva",
    "edad": 33,
    "id_pais": 1
  }
}

###

# Eliminar un proveedor
DELETE http://localhost:3000/api/cliente/e48a4358-8b92-44a2-a7ce-ca2935b48a82 HTTP/1.1


###
# TODO: PRODUCTO ENDPOINTS

# Obtener todos los productos
GET http://localhost:3000/api/producto HTTP/1.1

###

# Obtener un producto por ID
GET http://localhost:3000/api/producto/1 HTTP/1.1

###

# Crear un nuevo producto
POST http://localhost:3000/api/producto HTTP/1.1
Content-Type: application/json

{
  "nombre": "Camiseta deportiva",
  "descripcion": "Camiseta ligera para entrenamiento",
  "instrucciones_de_cuidado": "Lavar a mano con agua fría",
  "cantidad_stock": 50,
  "id_categoria": 1
}

###

# Actualizar un producto (PATCH)
PATCH http://localhost:3000/api/producto/1 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Mochila escolar",
  "descripcion": "Mochila resistente con varios compartimentos y correas ajustables",
  "instrucciones_de_cuidado": "Lavar a mano con agua fría y jabón neutro",
  "cantidad_stock": 120,
  "id_categoria": 1
}

###

# Eliminar un producto
DELETE http://localhost:3000/api/producto/2 HTTP/1.1


###
# TODO: PRODUCTO COMPLETO ENDPOINTS

# Obtener todos los productos completos
GET http://localhost:3000/api/productocompleto HTTP/1.1

###

# Obtener un producto completo por ID
GET http://localhost:3000/api/productocompleto/2 HTTP/1.1

###

# Crear un nuevo producto completo
POST http://localhost:3000/api/productocompleto HTTP/1.1
Content-Type: application/json

{
  "id_producto": 1,
  "id_talla": 1,
  "id_color": 1,
  "precio": 59999.990,
  "foto": "camiseta_azul.png",
  "cantidad": 200,
  "activo": true
}

###

# Actualizar un producto completo (PATCH)
PATCH http://localhost:3000/api/productocompleto/4 HTTP/1.1
Content-Type: application/json

{
  "id_producto": 3,
  "id_talla": 1,
  "id_color": 1,
  "precio": 5111,
  "foto": "11111.png",
  "cantidad": 50,
  "activo": true
}

###

# Eliminar un producto completo
DELETE http://localhost:3000/api/productocompleto/5 HTTP/1.1


###
# TODO: VETAS  ENDPOINTS

# Obtener todos las VETAS
GET http://localhost:3000/api/venta HTTP/1.1

###

# Obtener un ventas por ID
GET http://localhost:3000/api/venta/2 HTTP/1.1

###

# Crear un nuevo venta 
POST http://localhost:3000/api/venta HTTP/1.1
Content-Type: application/json

{
  "id_cliente": "cf32d55d-d573-41a2-9656-81cee3110304",
  "id_usuario": "28be75b9-ce1c-44e8-a1f0-d777a93caece",
  "fecha": "2025-09-06T12:00:00.000Z",
  "articulosVenta": [
    {
      "id_pxc": 3,
      "cantidad_vendida": 5
    },
    {
      "id_pxc": 4,
      "cantidad_vendida": 5
    }

  ]
  
}

###

# Eliminar un venta
DELETE http://localhost:3000/api/venta/8 HTTP/1.1


###
# TODO: COMPRAS ENDPOINTS

# Obtener todas las compras
GET http://localhost:3000/api/compra HTTP/1.1

###

# Obtener una compra por ID
GET http://localhost:3000/api/compra/3 HTTP/1.1

###

# Crear una nueva compra
POST http://localhost:3000/api/compra HTTP/1.1
Content-Type: application/json

{
  "id_proveedor": "1",
  "id_usuario": "28be75b9-ce1c-44e8-a1f0-d777a93caece",
  "fecha": "2025-09-06T12:00:00.000Z",
  "articulosCompra": [
    {
      "id_pxc": 3,
      "cantidad": 10
    },
    {
      "id_pxc": 4,
      "cantidad": 20
    }
  ]
}

###

# Eliminar una compra
DELETE http://localhost:3000/api/compra/6 HTTP/1.1


# TODO: PRODUCTOS POR COMPRA ENDPOINTS

### Obtener todos los artículos de una compra (por id_compra_inventario)
GET http://localhost:3000/api/productoxcompras?id_compra_inventario=2 HTTP/1.1

###

### Obtener todos los id_axc de una compra
GET http://localhost:3000/api/productoxcompras/ids/2 HTTP/1.1

###

### Obtener un artículo de compra por ID (id_axc)
GET http://localhost:3000/api/productoxcompras/2 HTTP/1.1

###

### Crear un artículo de compra
POST http://localhost:3000/api/productoxcompras HTTP/1.1
Content-Type: application/json

{
  "id_compra_inventario": 2,
  "id_pxc": 7,
  "cantidad": 15
}

###

### Actualizar un artículo de compra
PATCH http://localhost:3000/api/productoxcompras/12 HTTP/1.1
Content-Type: application/json

{
  "cantidad": 10,
  "id_pxc": 6
}

###

### Eliminar un artículo de compra
DELETE http://localhost:3000/api/productoxcompras/12 HTTP/1.1

